fin = open("%userprofile%\\.lunarclient\\solartweaks\\config.json", "rt")
data = fin.read()
data = data.replace('wss://assetserver.lunarclientprod.com/connect', 'wss://socket.solartweaks.com')
fin.close()
fin = open("config.json", "wt")
fin.write(data)
fin.close()
